const $ = s => document.querySelector(s);
const voices = [
  {name:'KICK',key:'A',file:'kick',color:'#d5f75b'}, {name:'SNARE',key:'S',file:'snare',color:'#d5f75b'},
  {name:'CLAP',key:'D',file:'clap',color:'#a9d781'}, {name:'CLOSED HH',key:'F',file:'hat',color:'#70dddf'},
  {name:'OPEN HH',key:'J',file:'openhat',color:'#70dddf'}, {name:'LOW TOM',key:'K',file:'tom',color:'#76acb7'},
  {name:'RIM',key:'L',file:'rim',color:'#d99db9'}, {name:'COWBELL',key:';',file:'cowbell',color:'#d99db9'}
];
const patterns = {
 ghost:[[0,4,8,12],[4,12],[12],[0,2,4,6,8,10,12,14],[7,15],[10],[],[3,11]],
 night:[[0,4,8,12],[4,12],[4,12],[0,2,4,6,8,10,12,14],[2,6,10,14],[],[7,15],[10]],
 broken:[[0,3,6,10],[4,12],[14],[0,2,5,6,8,10,13,14],[7,15],[9,11],[2,10],[]],
 empty:Array.from({length:8},()=>[])
};
let pattern = patterns.ghost.map(row=>Array.from({length:16},(_,i)=>row.includes(i)));
let audio, master, filter, analyser, buffers=[], loading, playing=false, timer, step=0, nextTime=0, bpm=120, swing=0, energy=0, activeStep=-1, scheduled=[], sources=new Set();
let presetName='ghost';
try { const saved=JSON.parse(localStorage.getItem('ghost-frequency-v1')); if(saved && Array.isArray(saved.pattern) && saved.pattern.length===8 && saved.pattern.every(r=>Array.isArray(r)&&r.length===16&&r.every(v=>typeof v==='boolean'))){pattern=saved.pattern;bpm=Math.max(50,Math.min(200,Number(saved.bpm)||120));swing=Math.max(0,Math.min(60,Number(saved.swing)||0));presetName='custom';} } catch {}
$('#bpm').value=bpm;$('#screen-bpm').innerHTML=`${bpm}<small>BPM</small>`;$('#swing').value=swing;$('#swing-value').textContent=swing+'%';
if(presetName==='custom'){const option=new Option('05 / МОЙ ПАТТЕРН','custom');$('#preset').add(option);$('#preset').value='custom';$('#screen-mode').textContent='SAVED PATTERN';}
voices.forEach((v,i)=>{const b=document.createElement('button');b.className='pad';b.style.setProperty('--pad-color',v.color);b.innerHTML=`<kbd>${v.key}</kbd><strong>${v.name}</strong>`;b.setAttribute('aria-label',`${v.name}, клавиша ${v.key}`);b.addEventListener('pointerdown',e=>{e.preventDefault();trigger(i)});b.addEventListener('click',e=>{if(e.detail===0)trigger(i)});$('#pads').append(b)});
const grid=$('#sequence-grid');grid.append(document.createElement('span'));
for(let i=0;i<16;i++){const n=document.createElement('span');n.className='step-number';n.textContent=String(i+1).padStart(2,'0');grid.append(n)}
voices.forEach((v,row)=>{const l=document.createElement('button');l.className='track-label';l.style.setProperty('--track-color',v.color);l.innerHTML=`<kbd>${v.key}</kbd><i></i>${v.name}`;l.setAttribute('aria-label',`Прослушать ${v.name}`);l.onclick=()=>trigger(row);grid.append(l);for(let col=0;col<16;col++){const b=document.createElement('button');b.className='step'+(Math.floor(col/4)%2===0?' beat-group':'');b.style.setProperty('--track-color',v.color);b.dataset.row=row;b.dataset.col=col;b.setAttribute('aria-label',`${v.name}, шаг ${col+1}`);b.onclick=()=>{pattern[row][col]=!pattern[row][col];refresh();$('#pattern-status').textContent='ПАТТЕРН ИЗМЕНЁН • СОХРАНИ СВОЙ РИТМ'};grid.append(b)}});
function refresh(){document.querySelectorAll('.step').forEach(b=>{const on=pattern[b.dataset.row][b.dataset.col];b.classList.toggle('on',on);b.setAttribute('aria-pressed',on)})}refresh();
const sampleData=Promise.all(voices.map(async v=>{const response=await fetch(`./assets/audio/${v.file}.mp3`);if(!response.ok)throw new Error('Sample not found');return response.arrayBuffer()}));
sampleData.then(()=>{$('#system-status').textContent='СИСТЕМА ГОТОВА / 8 ГОЛОСОВ'}).catch(()=>{$('#system-status').textContent='ОШИБКА ЗАГРУЗКИ ЗВУКОВ — ОБНОВИ СТРАНИЦУ'});
async function initAudio(){
 if(!audio){audio=new AudioContext();master=audio.createGain();master.gain.value=Number($('#volume').value)/100*.8;filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=180*Math.pow(20000/180,Number($('#tone').value)/100);analyser=audio.createAnalyser();analyser.fftSize=1024;const limiter=audio.createDynamicsCompressor();limiter.threshold.value=-9;limiter.knee.value=6;limiter.ratio.value=12;limiter.attack.value=.003;limiter.release.value=.12;filter.connect(master);master.connect(limiter);limiter.connect(analyser);analyser.connect(audio.destination);loading=sampleData.then(data=>Promise.all(data.map(a=>audio.decodeAudioData(a.slice(0))))).then(b=>buffers=b)}
 await audio.resume();await loading;
}
function sound(i,time){const source=audio.createBufferSource();source.buffer=buffers[i];source.connect(filter);sources.add(source);source.onended=()=>sources.delete(source);source.start(time);}
const hitTimers=[];
function flash(i){energy=Math.min(1,energy+.45);const p=$('#pads').children[i];p.classList.add('hit');clearTimeout(hitTimers[i]);hitTimers[i]=setTimeout(()=>p.classList.remove('hit'),120);$('#last-hit').textContent=voices[i].name+' / SIGNAL DETECTED_';}
async function trigger(i){try{await initAudio();sound(i,audio.currentTime);flash(i)}catch{$('#system-status').textContent='АУДИО НЕДОСТУПНО — ОБНОВИ СТРАНИЦУ'}}
function scheduler(){while(nextTime<audio.currentTime+.12){const hits=[];pattern.forEach((row,i)=>{if(row[step]){sound(i,nextTime);hits.push(i)}});scheduled.push({time:nextTime,step,hits});const duration=60/bpm/4;nextTime+=duration*(1+(step%2===0?1:-1)*swing/100);step=(step+1)%16}}
let starting=false;
async function togglePlay(){if(starting)return;if(playing){stop();return}starting=true;try{await initAudio();playing=true;step=0;nextTime=audio.currentTime+.05;$('#play').innerHTML='<span>■</span> STOP';$('#play').setAttribute('aria-label','Остановить секвенсор');$('#screen-play').textContent='● PLAYING';$('#pattern-status').textContent='СЕКВЕНСОР ИГРАЕТ';scheduler();timer=setInterval(scheduler,25)}catch{$('#system-status').textContent='АУДИО НЕДОСТУПНО'}finally{starting=false}}
function stop(){playing=false;clearInterval(timer);scheduled=[];sources.forEach(s=>{try{s.stop()}catch{}});sources.clear();$('#play').innerHTML='<span>▶</span> PLAY';$('#play').setAttribute('aria-label','Запустить секвенсор');$('#screen-play').textContent='● STANDBY';$('#pattern-status').textContent='ВОСПРОИЗВЕДЕНИЕ ОСТАНОВЛЕНО';setStep(-1);$('#beat-count').innerHTML='01<span> / 16</span>'}
function setStep(s){activeStep=s;document.querySelectorAll('.step').forEach(b=>b.classList.toggle('current',Number(b.dataset.col)===s));document.querySelectorAll('.step-number').forEach((b,i)=>b.classList.toggle('active',i===s));if(s>=0)$('#beat-count').innerHTML=String(s+1).padStart(2,'0')+'<span> / 16</span>'}
$('#play').onclick=togglePlay;
function changeBpm(value){bpm=Math.max(50,Math.min(200,Math.round(Number(value)||120)));$('#bpm').value=bpm;$('#screen-bpm').innerHTML=`${bpm}<small>BPM</small>`}
$('#bpm').oninput=e=>{const n=Number(e.target.value);if(n>=50&&n<=200){bpm=Math.round(n);$('#screen-bpm').innerHTML=`${bpm}<small>BPM</small>`}};$('#bpm').onchange=e=>changeBpm(e.target.value);$('#slower').onclick=()=>changeBpm(bpm-1);$('#faster').onclick=()=>changeBpm(bpm+1);
$('#swing').oninput=e=>{swing=Number(e.target.value);$('#swing-value').textContent=swing+'%'};
$('#volume').oninput=e=>{if(master)master.gain.setTargetAtTime(Number(e.target.value)/100*.8,audio.currentTime,.015)};
$('#tone').oninput=e=>{if(filter)filter.frequency.setTargetAtTime(180*Math.pow(20000/180,Number(e.target.value)/100),audio.currentTime,.02)};
$('#preset').onchange=e=>{if(!patterns[e.target.value])return;pattern=patterns[e.target.value].map(r=>Array.from({length:16},(_,i)=>r.includes(i)));refresh();$('#screen-mode').textContent='PATTERN A.'+String(e.target.selectedIndex+1).padStart(2,'0');$('#pattern-status').textContent='ПАТТЕРН ЗАГРУЖЕН'};
$('#clear').onclick=()=>{pattern=patterns.empty.map(()=>Array(16).fill(false));$('#preset').value='empty';$('#screen-mode').textContent='BLANK PATTERN';refresh();$('#pattern-status').textContent='ЧИСТЫЙ ЛИСТ — СОЗДАЙ СВОЙ БИТ'};
$('#save').onclick=()=>{try{localStorage.setItem('ghost-frequency-v1',JSON.stringify({pattern,bpm,swing}));$('#pattern-status').textContent='СОХРАНЕНО В ЭТОМ БРАУЗЕРЕ ✓'}catch{$('#pattern-status').textContent='БРАУЗЕР НЕ РАЗРЕШИЛ СОХРАНЕНИЕ'}};
$('#explode').onclick=()=>{const open=$('#machine').classList.toggle('exploded');$('#explode').setAttribute('aria-pressed',open);$('#explode').innerHTML=`<span class="layers-icon">▱</span> ${open?'СОБРАТЬ':'РАЗОБРАТЬ'} <span>${open?'↙':'↗'}</span>`;$('#assembly-state').textContent=open?'02 / EXPLODED':'01 / ENCLOSED'};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$('#stage').addEventListener('pointermove',e=>{if(e.pointerType==='touch'||reduced)return;const r=$('#stage').getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$('#machine').style.transform=`rotateX(${25-y*9}deg) rotateY(${-6+x*13}deg) rotateZ(${-5+x*3}deg)`});$('#stage').addEventListener('pointerleave',()=>$('#machine').style.transform='');
$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=$('#start-playing').onclick=()=>$('#help-dialog').close();
window.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||$('#help-dialog').open||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay();return}const codes=['KeyA','KeyS','KeyD','KeyF','KeyJ','KeyK','KeyL','Semicolon'];const i=codes.indexOf(e.code);if(i>=0){e.preventDefault();trigger(i)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)stop()});
// A native WebGL fragment shader: a perspective floor and sound-reactive signal waves.
const canvas=$('#atmosphere');let gl;try{gl=canvas.getContext('webgl',{alpha:true,antialias:false})}catch{}
let program, uniforms;
if(gl){try{const vertex='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';const fragment=`precision mediump float;uniform vec2 resolution;uniform float time;uniform float energy;void main(){vec2 uv=gl_FragCoord.xy/resolution;vec2 p=uv-.5;p.x*=resolution.x/resolution.y;float glow=exp(-length(p-vec2(.1,.0))*3.);float w=sin(p.x*12.+time*.23)*.02+sin(p.x*25.-time*.2)*.008;float signal=.0015/(abs(p.y-w+.06)+.004);float scan=pow(.5+.5*sin(uv.y*resolution.y*1.6),8.)*.012;vec3 c=vec3(.008,.032,.034)+vec3(.015,.08,.073)*glow+vec3(.04,.25,.24)*signal*(.15+energy*.8);c+=scan;gl_FragColor=vec4(c,1.);}`;const compile=(type,src)=>{const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh};program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('WebGL link');gl.useProgram(program);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const p=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);uniforms={resolution:gl.getUniformLocation(program,'resolution'),time:gl.getUniformLocation(program,'time'),energy:gl.getUniformLocation(program,'energy')};const resize=()=>{const d=Math.min(devicePixelRatio,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d;gl.viewport(0,0,canvas.width,canvas.height)};resize();addEventListener('resize',resize)}catch{gl=null;canvas.style.display='none'}}
const ctx=$('#scope').getContext('2d'), wave=new Uint8Array(1024);let lastFrame=0;
function frame(t){requestAnimationFrame(frame);if(document.hidden)return;if(audio){while(scheduled.length&&scheduled[0].time<=audio.currentTime){const event=scheduled.shift();setStep(event.step);event.hits.forEach(flash)}}if(t-lastFrame<32)return;lastFrame=t;energy*=.89;if(gl&&!reduced){gl.uniform2f(uniforms.resolution,canvas.width,canvas.height);gl.uniform1f(uniforms.time,t/1000);gl.uniform1f(uniforms.energy,energy);gl.drawArrays(gl.TRIANGLES,0,6)}ctx.clearRect(0,0,480,100);ctx.strokeStyle='#b8ee69';ctx.lineWidth=2;ctx.shadowColor='#b8ee69';ctx.shadowBlur=6;ctx.beginPath();if(analyser)analyser.getByteTimeDomainData(wave);for(let x=0;x<480;x++){const y=analyser?(wave[Math.floor(x/480*1024)]-128)/128*43+50:50+Math.sin(x*.09)*(reduced?2:3+Math.sin(x*.03+t*.001)*3);x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}requestAnimationFrame(frame);
